POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhdXJpIiwiaWQiOiI2MGFlNGI2ZWRmMjM3MjUzMWY1NjQ4YTQiLCJpYXQiOjE2MjIwOTkzNDl9.aAXYLe_4tIWqMv3VH7fLCWUI-dadAGXtaSJm8n7NNN0

{
        "title": "refaktoroitukäyttäjä?",
       "author": "meitsi",
        "url": "huhheijakkaa",
        "likes": 11
        
}